WebApplication/Controllers/GuestController.cs
using System.Linq;
using System.Web.Mvc;
using WebApplication.BLL.Interfaces;
using WebApplication.WEB.Models;

namespace WebApplication.Controllers
{
    /// <summary>
    /// Controller for showing and sending users feedback.
    /// /// </summary>
    public class GuestController : Controller
    {
        /// <summary>
        /// Service for working with user feedback.
        /// </summary>
        private readonly IFeedbackService _feedbacksService;

        public GuestController(IFeedbackService service)
        {
            _feedbacksService = service;
        }

        /// <summary>
        /// The start view for users feedback.
        /// </summary>
        /// <returns>
        /// View with all feedback and feedback form.
        /// </returns>
        public ActionResult Index(int page = 1)
        {
            int pageSize = 3;
            var feedbackPerPages = _feedbacksService.GetFeedbacks().Skip((page - 1) * pageSize).Take(pageSize);
            var pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = _feedbacksService.GetFeedbacks().Count };
            var ivm = new FeedbackViewModel { PageInfo = pageInfo, Feedback = feedbackPerPages.ToList() };
            return View(ivm);
        }

        /// <summary>
        /// Check if the feedback is valid and save it in database.
        /// </summary>
        /// <param name="feedback">
        /// User feedback from the form. 
        /// </param>
        /// <returns>
        /// View with new feedback. Otherwise show client error massage.
        /// </returns>
        [HttpPost]
        public ActionResult SendFeedback(FeedbackViewModel feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbacksService.AddFeedback(feedback.FeedbackObject);
                return RedirectToAction("Index");
            }

            int pageSize = 3;
            int page = 1;
            feedback.Feedback = _feedbacksService.GetFeedbacks();
            feedback.PageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = _feedbacksService.GetFeedbacks().Count };
            return View("Index", feedback);
        }
    }
}

WebApplication/Controllers/QuestionnaireController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplication.BLL.DTO;
using WebApplication.BLL.Interfaces;
using WebApplication.WEB.Models;

namespace WebApplication.Controllers
{
    /// <summary>
    /// Controller for working with user questionnaire.
    /// </summary>
    public class QuestionnaireController : Controller
    {
        private readonly IQuestionnaireService _questionnaireService;

        public QuestionnaireController(IQuestionnaireService service)
        {
            _questionnaireService = service;
        }

        /// <summary>
        /// Show view for questionnaire.
        /// </summary>
        /// <returns>
        /// View for filling in the data in the questionnaire.
        /// </returns>
        [HttpGet]
        public ActionResult QuestionnaireRegister()
        {
            return View(new QuestionnaireViewModel());
        }

        /// <summary>
        /// Show the result of questionnaire.
        /// </summary>
        /// <param name="questionnaire">
        /// Object from View with inputed data.
        /// </param>
        /// <returns>
        /// View with the filling data.
        /// </returns>
        [HttpPost]
        public ActionResult QuestionnaireRegister(QuestionnaireViewModel questionnaire)
        {
            if (string.IsNullOrEmpty(questionnaire.FName))
                ModelState.AddModelError("FName", "Please enter your first name");

            if (string.IsNullOrEmpty(questionnaire.LName))
                ModelState.AddModelError("LName", "Please enter your last name");

            if (!questionnaire.IsConfirmed)
                ModelState.AddModelError("IsConfirmed", "You must accept the terms");

            if (ModelState.IsValid)
            {
                ViewBag.FirstName = questionnaire.FName;
                ViewBag.LastName = questionnaire.LName;
                ViewBag.Sex = questionnaire.Sex;
                List<NetworkDTO> socailNetworkLists = new List<NetworkDTO>();
                for (int i = 0; i < questionnaire.Networks.Count; i++)
                {
                    if (questionnaire.Networks[i].IsSelected)
                        socailNetworkLists.Add(new NetworkDTO { Name = questionnaire.Networks[i].Name });
                }
                ViewBag.SocailNetworkLists = socailNetworkLists;
                ViewBag.Mark = questionnaire.Mark;
                _questionnaireService.AddQuestionnaire(questionnaire.FName, questionnaire.FName, questionnaire.Sex,
                    questionnaire.Mark, socailNetworkLists);
                return View("QuestionnaireCompleted");
            }

            return View(new QuestionnaireViewModel());
        }

    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Library</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/font-awesome.css")
    @Styles.Render("~/Content/font-awesome.min.css")
</head>
<body>
    <header>
        <div class="row">
            <div class="col-md-1">
                <a href="/Home/Index"><img src="~/Content/Images/Logo.svg" class="img-fluid img-thumbnail rounded float-left"></a>
            </div>
            <div class="col-md-11">
                <h1 class="title">
                    My Library
                </h1>
            </div>
        </div>
    </header>
    <main>
        <div class="row">
            <div class="col-md-9 offset-2">
                <div class="content-main">
                    @RenderBody()
                </div>
                <div class="right-sidebar">
                    @Html.ActionLink("Головна", "index", "Home", null, new { @class = "nav-item" })
                    @Html.ActionLink("Гостьова", "index", "Guest", null, new { @class = "nav-item" })
                    @Html.ActionLink("Анкета", "QuestionnaireRegister", "Questionnaire", null, new { @class = "nav-item" })
                </div>
            </div>
        </div>
    </main>
    <a id="back-to-top" href="#" class="btn btn-light btn-lg back-to-top" role="button">
        <i class="fa fa-arrow-circle-up"></i>
    </a>
    <footer>
        <div class="col-md-12">
            <span id="copyright">&#169; Serhii Yurko sergiyyurko7@gmail.com</span>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/BackTop.js")
</body>
</html>